# yaml-language-server: $schema=https://trovu.net/schema/config.yml
#
# Documentation:
# https://trovu.net/docs/users/advanced/#custom-configuration

namespaces:
- github: .
  name: carlf
- o
- en
- .us
# defaultKeyword: g 
defaultKeyword: kg
language: en
country: us
